version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3100:3000"
    depends_on:
      - backend
    networks:
      - db-net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8100:8000"
    depends_on:
      - db
    networks:
      - db-net
volumes:
  db_data:

networks:
  db-net:
    external: true
