name: Auto Deploy on Push

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub (Optional)
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: true
        
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          # Navigate to project directory
          cd /path/to/your/project || { echo "Project directory not found"; exit 1; }
          
          # Pull latest changes
          git pull origin master
          
          # Stop existing containers
          docker compose down
          
          # Rebuild and start containers
          docker compose build --no-cache
          docker compose up -d
          
          # Clean up old images
          docker image prune -f
          
          # Show running containers
          docker compose ps